/* HFUT Campus Smart Q&A — 前端交互脚本 */

const messagesEl   = document.getElementById('messages');
const questionEl   = document.getElementById('question');
const endpointEl   = document.getElementById('endpoint');
const studentIdEl  = document.getElementById('student-id');
const apiKeyEl     = document.getElementById('api-key');
const sendBtn      = document.getElementById('send-btn');
const resetBtn     = document.getElementById('reset-btn');
const modeTag      = document.getElementById('mode-tag');
const autoTag      = document.getElementById('auto-tag');
const toolsTag     = document.getElementById('tools-tag');
const toolResultsEl = document.getElementById('tool-results');
const mcpBadge     = document.getElementById('mcp-badge');
const ragBadge     = document.getElementById('rag-badge');
const memoryCount  = document.getElementById('memory-count');
const currentSid   = document.getElementById('current-sid');

let streamAbortController = null;
let messageCount = 0;

/* ---- 工具函数 ---- */

function escapeHtml(text) {
  return String(text)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
}

function addMessage(role, text, meta = '') {
  const wrapper = document.createElement('div');
  wrapper.className = `message ${role}`;
  wrapper.innerHTML =
    `<div class="msg-avatar">${role === 'user' ? '你' : 'AI'}</div>` +
    `<div class="msg-body">` +
      `<div class="msg-bubble">${escapeHtml(text).replaceAll('\n', '<br>')}</div>` +
      `${meta ? `<div class="msg-meta">${escapeHtml(meta)}</div>` : ''}` +
    `</div>`;
  messagesEl.appendChild(wrapper);
  messagesEl.scrollTop = messagesEl.scrollHeight;
  return wrapper;
}

function addStreamingMessage() {
  const wrapper = document.createElement('div');
  wrapper.className = 'message assistant';
  wrapper.innerHTML =
    `<div class="msg-avatar">AI</div>` +
    `<div class="msg-body">` +
      `<div class="msg-bubble"><span class="streaming-text"></span></div>` +
      `<div class="msg-meta">流式输出中…</div>` +
    `</div>`;
  messagesEl.appendChild(wrapper);
  messagesEl.scrollTop = messagesEl.scrollHeight;
  return wrapper;
}

function appendToStreaming(wrapper, text) {
  const span = wrapper.querySelector('.streaming-text');
  span.textContent += text;
  messagesEl.scrollTop = messagesEl.scrollHeight;
}

function finalizeStreaming(wrapper, meta) {
  const metaEl = wrapper.querySelector('.msg-meta');
  metaEl.textContent = meta || '流式输出完成';
  // 移除 streaming 包装
  const span = wrapper.querySelector('.streaming-text');
  if (span) {
    const bubble = span.closest('.msg-bubble');
    bubble.innerHTML = escapeHtml(span.textContent).replaceAll('\n', '<br>');
  }
}

/* ---- 状态面板更新 ---- */

function setStatus({ mode, autoGenerated, toolsUsed, toolResults }) {
  modeTag.textContent = mode || '-';
  autoTag.textContent = autoGenerated ? '是' : '否';
  toolsTag.textContent = toolsUsed?.length ? toolsUsed.join('、') : '-';

  if (toolResults && Object.keys(toolResults).length) {
    toolResultsEl.textContent = JSON.stringify(toolResults, null, 2);
  } else {
    toolResultsEl.textContent = '本次未返回工具明细或未命中工具。';
  }

  // MCP / RAG 状态 badge
  if (mode === 'mcp') {
    mcpBadge.textContent = '命中';
    mcpBadge.className = 'status-badge ok';
    ragBadge.textContent = '未使用';
    ragBadge.className = 'status-badge';
  } else if (mode === 'rag') {
    mcpBadge.textContent = '未命中';
    mcpBadge.className = 'status-badge';
    ragBadge.textContent = '命中';
    ragBadge.className = 'status-badge ok';
  } else {
    mcpBadge.textContent = '未命中';
    mcpBadge.className = 'status-badge';
    ragBadge.textContent = '未命中';
    ragBadge.className = 'status-badge';
  }
}

function apiHeaders() {
  return {
    'Content-Type': 'application/json',
    'X-API-Key': apiKeyEl.value.trim() || 'campus-qa-dev-key',
  };
}

/* ---- API 调用 ---- */

async function askStandard(question, endpoint, student_id) {
  const res = await fetch(endpoint, {
    method: 'POST',
    headers: apiHeaders(),
    body: JSON.stringify({ question, student_id }),
  });
  const data = await res.json();
  if (!res.ok) {
    throw new Error(data?.detail || `HTTP ${res.status}`);
  }
  return data;
}

async function askStream(question, student_id, wrapper) {
  streamAbortController = new AbortController();

  const res = await fetch('/ask/stream', {
    method: 'POST',
    headers: apiHeaders(),
    body: JSON.stringify({ question, student_id }),
    signal: streamAbortController.signal,
  });

  if (!res.ok) {
    const data = await res.json().catch(() => ({}));
    throw new Error(data?.detail || `HTTP ${res.status}`);
  }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buffer = '';
  let meta = null;

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split('\n');
    buffer = lines.pop() || '';

    for (const line of lines) {
      if (!line.startsWith('data: ')) continue;
      const payload = JSON.parse(line.slice(6));

      if (payload.event === 'meta') {
        meta = payload;
        setStatus(meta);
        finalizeStreaming(wrapper,
          `模式：${payload.mode}${payload.auto_generated ? ' · 自动生成' : ''}`);
      } else if (payload.event === 'token') {
        appendToStreaming(wrapper, payload.token);
      } else if (payload.event === 'done') {
        finalizeStreaming(wrapper,
          meta ? `模式：${meta.mode} · 流式完成` : '流式完成');
      }
    }
  }

  streamAbortController = null;
}

/* ---- 主流程 ---- */

async function ask() {
  const question = questionEl.value.trim();
  const endpoint = endpointEl.value;
  const student_id = studentIdEl.value.trim() || 'S001';

  if (!question) {
    questionEl.focus();
    return;
  }

  // 取消正在进行的流式请求
  if (streamAbortController) {
    streamAbortController.abort();
    streamAbortController = null;
  }

  sendBtn.disabled = true;
  sendBtn.textContent = '发送中…';
  addMessage('user', question, `接口：${endpoint} · 学生：${student_id}`);
  messageCount++;
  updateMemoryCount();

  const isStreaming = endpoint === '/ask/stream';

  try {
    if (isStreaming) {
      const wrapper = addStreamingMessage();
      await askStream(question, student_id, wrapper);
    } else {
      const data = await askStandard(question, endpoint, student_id);
      const meta = `模式：${data.mode || '-'}${data.auto_generated ? ' · 自动生成' : ''}`;
      addMessage('assistant', data.answer, meta);
      setStatus(data);
    }
  } catch (error) {
    if (error.name === 'AbortError') return;
    addMessage('assistant', `请求失败：${error.message}`, '错误');
    setStatus({ mode: 'error', autoGenerated: false, toolsUsed: [], toolResults: {} });
  } finally {
    sendBtn.disabled = false;
    sendBtn.textContent = '发 送';
    questionEl.focus();
  }
}

/* ---- 重置对话 ---- */

async function resetConversation() {
  const student_id = studentIdEl.value.trim() || 'S001';

  if (streamAbortController) {
    streamAbortController.abort();
    streamAbortController = null;
  }

  try {
    const res = await fetch('/reset', {
      method: 'POST',
      headers: apiHeaders(),
      body: JSON.stringify({ student_id }),
    });
    const data = await res.json();
    if (data.status === 'ok') {
      messageCount = 0;
      updateMemoryCount();
      modeTag.textContent = '已重置';
      toolsTag.textContent = '-';
      toolResultsEl.textContent = '对话历史已清除。';
      addMessage('assistant', `已清除 ${student_id} 的对话历史，可以重新开始提问了。`, '系统');
    }
  } catch (error) {
    addMessage('assistant', `重置失败：${error.message}`, '错误');
  }
}

function updateMemoryCount() {
  memoryCount.textContent = messageCount;
}

/* ---- 事件绑定 ---- */

// 预设按钮 — 左侧工具网格 + 快捷 chips
document.querySelectorAll('[data-preset]').forEach((btn) => {
  btn.addEventListener('click', () => {
    questionEl.value = btn.getAttribute('data-preset');
    questionEl.focus();

    // 左侧工具网格的 active 样式
    if (btn.classList.contains('tool-item')) {
      document.querySelectorAll('.tool-item').forEach(item => item.classList.remove('active'));
      btn.classList.add('active');
    }
  });
});

// 顶部导航锚点滚动
document.querySelectorAll('.top-nav-link').forEach(link => {
  link.addEventListener('click', (e) => {
    e.preventDefault();
    const target = document.querySelector(link.getAttribute('href'));
    if (target) {
      target.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
    document.querySelectorAll('.top-nav-link').forEach(l => l.classList.remove('active'));
    link.classList.add('active');
  });
});

studentIdEl.addEventListener('input', () => {
  currentSid.textContent = studentIdEl.value.trim() || 'S001';
});

sendBtn.addEventListener('click', ask);
resetBtn.addEventListener('click', resetConversation);

questionEl.addEventListener('keydown', (e) => {
  if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') ask();
});
