/* 合肥工业大学 · 校园智能问答 — 前端交互 */

const $ = (s) => document.querySelector(s);
const $$ = (s) => document.querySelectorAll(s);

const messagesEl   = $('#messages');
const questionEl   = $('#question');
const endpointEl   = $('#endpoint');
const studentIdEl  = $('#student-id');
const apiKeyEl     = $('#api-key');
const sendBtn      = $('#send-btn');
const resetBtn     = $('#reset-btn');
const modeTag      = $('#mode-tag');
const autoTag      = $('#auto-tag');
const toolsTag     = $('#tools-tag');
const toolResults  = $('#tool-results');
const mcpBadge     = $('#mcp-badge');
const ragBadge     = $('#rag-badge');
const memoryCount  = $('#memory-count');
const currentSid   = $('#current-sid');

let streamCtrl = null;
let msgCount = 0;

/* ---- helpers ---- */
const esc = (t) => String(t).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');

function addMsg(role, text, meta) {
  const el = document.createElement('div');
  el.className = `msg ${role}`;
  el.innerHTML =
    `<div class="msg-avatar">${role==='user'?'你':'AI'}</div>` +
    `<div class="msg-bubble">${esc(text).replaceAll('\n','<br>')}</div>` +
    (meta ? `<div style="font-size:.76rem;color:var(--text-muted);padding:2px 4px">${esc(meta)}</div>` : '');
  messagesEl.appendChild(el);
  messagesEl.scrollTop = messagesEl.scrollHeight;
}

function addStreamMsg() {
  const el = document.createElement('div');
  el.className = 'msg assistant';
  el.innerHTML =
    `<div class="msg-avatar">AI</div>` +
    `<div class="msg-bubble"><span class="s-text"></span></div>` +
    `<div style="font-size:.76rem;color:var(--text-muted);padding:2px 4px">流式输出中…</div>`;
  messagesEl.appendChild(el);
  messagesEl.scrollTop = messagesEl.scrollHeight;
  return el;
}

function appendStream(el, text) {
  el.querySelector('.s-text').textContent += text;
  messagesEl.scrollTop = messagesEl.scrollHeight;
}

function finishStream(el, meta) {
  el.lastElementChild.textContent = meta || '完成';
  const span = el.querySelector('.s-text');
  if (span) {
    const bubble = el.querySelector('.msg-bubble');
    bubble.innerHTML = esc(span.textContent).replaceAll('\n','<br>');
  }
}

/* ---- status panel ---- */
function setStatus({mode, autoGenerated, toolsUsed, toolResults: tr}) {
  modeTag.textContent = mode || '-';
  autoTag.textContent = autoGenerated ? '是' : '否';
  toolsTag.textContent = toolsUsed?.length ? toolsUsed.join('、') : '-';
  toolResults.textContent = (tr && Object.keys(tr).length)
    ? JSON.stringify(tr, null, 2)
    : '未命中或未返回。';

  if (mode === 'mcp') {
    mcpBadge.textContent = '命中'; mcpBadge.className = 'badge on';
    ragBadge.textContent = '-'; ragBadge.className = 'badge';
  } else if (mode === 'rag') {
    mcpBadge.textContent = '-'; mcpBadge.className = 'badge';
    ragBadge.textContent = '命中'; ragBadge.className = 'badge on';
  } else {
    mcpBadge.textContent = '-'; mcpBadge.className = 'badge';
    ragBadge.textContent = '-'; ragBadge.className = 'badge';
  }
}

function headers() {
  return {
    'Content-Type': 'application/json',
    'X-API-Key': apiKeyEl.value.trim() || 'campus-qa-dev-key',
  };
}

/* ---- API ---- */
async function askNormal(question, endpoint, sid) {
  const res = await fetch(endpoint, {
    method:'POST', headers:headers(),
    body:JSON.stringify({question, student_id:sid}),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data?.detail || `HTTP ${res.status}`);
  return data;
}

async function askStream(question, sid, el) {
  streamCtrl = new AbortController();
  const res = await fetch('/ask/stream', {
    method:'POST', headers:headers(),
    body:JSON.stringify({question, student_id:sid}),
    signal:streamCtrl.signal,
  });
  if (!res.ok) {
    const d = await res.json().catch(()=>({}));
    throw new Error(d?.detail || `HTTP ${res.status}`);
  }
  const reader = res.body.getReader();
  const dec = new TextDecoder();
  let buf = '', meta = null;
  while (true) {
    const {done, value} = await reader.read();
    if (done) break;
    buf += dec.decode(value, {stream:true});
    const lines = buf.split('\n'); buf = lines.pop() || '';
    for (const line of lines) {
      if (!line.startsWith('data: ')) continue;
      const p = JSON.parse(line.slice(6));
      if (p.event === 'meta') { meta = p; setStatus(meta); finishStream(el, `模式：${p.mode}${p.auto_generated?' · 自动生成':''}`); }
      else if (p.event === 'token') appendStream(el, p.token);
      else if (p.event === 'done') finishStream(el, meta ? `模式：${meta.mode} · 完成` : '完成');
    }
  }
  streamCtrl = null;
}

/* ---- main ---- */
async function ask() {
  const q = questionEl.value.trim();
  const endpoint = endpointEl.value;
  const sid = studentIdEl.value.trim() || 'S001';
  if (!q) return questionEl.focus();

  if (streamCtrl) { streamCtrl.abort(); streamCtrl = null; }

  sendBtn.disabled = true; sendBtn.textContent = '…';
  addMsg('user', q, `接口：${endpoint} · ${sid}`);
  msgCount++; memoryCount.textContent = msgCount;

  try {
    if (endpoint === '/ask/stream') {
      const el = addStreamMsg();
      await askStream(q, sid, el);
    } else {
      const data = await askNormal(q, endpoint, sid);
      addMsg('assistant', data.answer, `模式：${data.mode||'-'}${data.auto_generated?' · 自动生成':''}`);
      setStatus(data);
    }
  } catch (e) {
    if (e.name === 'AbortError') return;
    addMsg('assistant', `请求失败：${e.message}`, '错误');
    setStatus({mode:'error',autoGenerated:false,toolsUsed:[],toolResults:{}});
  } finally {
    sendBtn.disabled = false; sendBtn.textContent = '发 送';
    questionEl.focus();
  }
}

async function resetConv() {
  const sid = studentIdEl.value.trim() || 'S001';
  if (streamCtrl) { streamCtrl.abort(); streamCtrl = null; }
  try {
    const res = await fetch('/reset', {method:'POST', headers:headers(), body:JSON.stringify({student_id:sid})});
    const data = await res.json();
    if (data.status === 'ok') {
      msgCount = 0; memoryCount.textContent = '0';
      modeTag.textContent = '已重置'; toolsTag.textContent = '-';
      toolResults.textContent = '对话历史已清除。';
      addMsg('assistant', `已清除 ${sid} 的对话历史。`, '系统');
    }
  } catch (e) {
    addMsg('assistant', `重置失败：${e.message}`, '错误');
  }
}

/* ---- events ---- */
$$('[data-preset]').forEach(btn => {
  btn.addEventListener('click', () => {
    questionEl.value = btn.dataset.preset;
    questionEl.focus();
    if (btn.classList.contains('tool-item')) {
      $$('.tool-item').forEach(i => i.classList.remove('active'));
      btn.classList.add('active');
    }
  });
});

// 顶部导航平滑滚动
$$('.top-nav-item').forEach(link => {
  link.addEventListener('click', e => {
    e.preventDefault();
    const t = document.querySelector(link.getAttribute('href'));
    if (t) t.scrollIntoView({behavior:'smooth',block:'start'});
    $$('.top-nav-item').forEach(l => l.classList.remove('active'));
    link.classList.add('active');
  });
});

studentIdEl.addEventListener('input', () => {
  currentSid.textContent = studentIdEl.value.trim() || 'S001';
});

sendBtn.addEventListener('click', ask);
resetBtn.addEventListener('click', resetConv);
questionEl.addEventListener('keydown', e => {
  if ((e.ctrlKey||e.metaKey) && e.key==='Enter') ask();
});
