/* 合肥工业大学 · 校园智能问答 — 前端交互 */

const $ = (s) => document.querySelector(s);
const $$ = (s) => document.querySelectorAll(s);

const messagesEl   = $('#messages');
const questionEl   = $('#question');
const endpointEl   = $('#endpoint');
const studentIdEl  = $('#student-id');
const apiKeyEl     = $('#api-key');
const sendBtn      = $('#send-btn');
const resetBtn     = $('#reset-btn');
const modeTag      = $('#mode-tag');
const autoTag      = $('#auto-tag');
const toolsTag     = $('#tools-tag');
const toolResults  = $('#tool-results');
const mcpBadge     = $('#mcp-badge');
const ragBadge     = $('#rag-badge');
const memoryCount  = $('#memory-count');
const currentSid   = $('#current-sid');
const themeBtn     = $('#theme-btn');

let streamCtrl = null;
let msgCount = 0;

/* ============================================================
   主题管理（暗色模式）
   ============================================================ */
function initTheme() {
  const saved = localStorage.getItem('campus-qa-theme');
  const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
  const theme = saved || (prefersDark ? 'dark' : 'light');
  applyTheme(theme);
}

function applyTheme(theme) {
  document.documentElement.setAttribute('data-theme', theme);
  const icon = themeBtn.querySelector('.theme-icon');
  if (icon) icon.textContent = theme === 'dark' ? '☀️' : '🌙';
  themeBtn.setAttribute('aria-label', theme === 'dark' ? '切换浅色模式' : '切换深色模式');
}

function toggleTheme() {
  const current = document.documentElement.getAttribute('data-theme');
  const next = current === 'dark' ? 'light' : 'dark';
  applyTheme(next);
  localStorage.setItem('campus-qa-theme', next);
}

/* ============================================================
   helpers
   ============================================================ */
const esc = (t) => String(t).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');

/**
 * 渲染 Markdown 为安全 HTML。
 * 使用 marked + DOMPurify；若 CDN 未加载则降级为转义纯文本。
 */
function renderMarkdown(text) {
  if (window.marked && window.DOMPurify) {
    try {
      marked.setOptions({ breaks: true, gfm: true });
      const raw = marked.parse(String(text));
      return window.DOMPurify.sanitize(raw, {
        ALLOWED_TAGS: ['p','br','strong','em','del','code','pre','blockquote',
          'ul','ol','li','h1','h2','h3','h4','h5','h6','a','table','thead',
          'tbody','tr','th','td','hr','span'],
        ALLOWED_ATTR: ['href','title'],
      });
    } catch (_) { /* 降级 */ }
  }
  return esc(text).replaceAll('\n', '<br>');
}

/* ---- 消息渲染 ---- */
function setBusy(busy) {
  messagesEl.setAttribute('aria-busy', busy ? 'true' : 'false');
}

function addMsg(role, text, meta, isError) {
  const el = document.createElement('div');
  el.className = `msg ${role}${isError ? ' error' : ''}`;
  const avatar = role === 'user' ? '你' : 'AI';
  // 用户消息始终转义（不渲染 Markdown，防注入）；助手消息渲染 Markdown
  const body = role === 'user'
    ? esc(text).replaceAll('\n', '<br>')
    : (isError ? esc(text).replaceAll('\n', '<br>') : renderMarkdown(text));
  el.innerHTML =
    `<div class="msg-avatar" aria-hidden="true">${avatar}</div>` +
    `<div class="msg-bubble${role === 'assistant' && !isError ? ' md' : ''}">${body}</div>` +
    (meta ? `<div class="typing-hint" style="padding:2px 4px">${esc(meta)}</div>` : '');
  messagesEl.appendChild(el);
  messagesEl.scrollTop = messagesEl.scrollHeight;
  return el;
}

/** 显示打字指示器，返回该消息元素，供后续替换 */
function showTyping() {
  const el = document.createElement('div');
  el.className = 'msg assistant';
  el.innerHTML =
    `<div class="msg-avatar" aria-hidden="true">AI</div>` +
    `<div class="msg-bubble"><div class="typing-dots" aria-label="正在思考"><span></span><span></span><span></span></div></div>`;
  messagesEl.appendChild(el);
  messagesEl.scrollTop = messagesEl.scrollHeight;
  return el;
}

/** 流式：把打字指示器替换为流式文本容器 */
function typingToStream(el) {
  const bubble = el.querySelector('.msg-bubble');
  if (bubble) bubble.innerHTML = '<span class="s-text"></span>';
  return el;
}

function appendStream(el, text) {
  const span = el.querySelector('.s-text');
  if (span) {
    span.textContent += text;
    messagesEl.scrollTop = messagesEl.scrollHeight;
  }
}

/** 流式完成：把纯文本流转为 Markdown 渲染 */
function finishStream(el, meta) {
  const span = el.querySelector('.s-text');
  const bubble = el.querySelector('.msg-bubble');
  if (span && bubble) {
    bubble.className = 'msg-bubble md';
    bubble.innerHTML = renderMarkdown(span.textContent);
  }
  if (meta) {
    const hint = document.createElement('div');
    hint.className = 'typing-hint';
    hint.style.padding = '2px 4px';
    hint.textContent = meta;
    el.appendChild(hint);
  }
}

/* ---- 状态面板 ---- */
function setStatus({mode, autoGenerated, toolsUsed, toolResults: tr}) {
  modeTag.textContent = mode || '-';
  autoTag.textContent = autoGenerated ? '是' : '否';
  toolsTag.textContent = toolsUsed?.length ? toolsUsed.join('、') : '-';
  toolResults.textContent = (tr && Object.keys(tr).length)
    ? JSON.stringify(tr, null, 2)
    : '未命中或未返回。';

  if (mode === 'mcp') {
    mcpBadge.textContent = '命中'; mcpBadge.className = 'badge on';
    ragBadge.textContent = '-'; ragBadge.className = 'badge';
  } else if (mode === 'rag') {
    mcpBadge.textContent = '-'; mcpBadge.className = 'badge';
    ragBadge.textContent = '命中'; ragBadge.className = 'badge on';
  } else if (mode === 'error') {
    mcpBadge.textContent = '错误'; mcpBadge.className = 'badge';
    ragBadge.textContent = '错误'; ragBadge.className = 'badge';
  } else {
    mcpBadge.textContent = '-'; mcpBadge.className = 'badge';
    ragBadge.textContent = '-'; ragBadge.className = 'badge';
  }
}

function headers() {
  return {
    'Content-Type': 'application/json',
    'X-API-Key': apiKeyEl.value.trim() || 'campus-qa-dev-key',
  };
}

/* ============================================================
   API
   ============================================================ */
async function askNormal(question, endpoint, sid) {
  const res = await fetch(endpoint, {
    method:'POST', headers:headers(),
    body:JSON.stringify({question, student_id:sid}),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data?.detail || `HTTP ${res.status}`);
  return data;
}

async function askStream(question, sid, el) {
  streamCtrl = new AbortController();
  const res = await fetch('/ask/stream', {
    method:'POST', headers:headers(),
    body:JSON.stringify({question, student_id:sid}),
    signal:streamCtrl.signal,
  });
  if (!res.ok) {
    const d = await res.json().catch(()=>({}));
    throw new Error(d?.detail || `HTTP ${res.status}`);
  }
  const reader = res.body.getReader();
  const dec = new TextDecoder();
  let buf = '', meta = null, firstToken = true;
  while (true) {
    const {done, value} = await reader.read();
    if (done) break;
    buf += dec.decode(value, {stream:true});
    const lines = buf.split('\n'); buf = lines.pop() || '';
    for (const line of lines) {
      if (!line.startsWith('data: ')) continue;
      const p = JSON.parse(line.slice(6));
      if (p.event === 'meta') {
        meta = p; setStatus(meta);
      } else if (p.event === 'token') {
        if (firstToken) { typingToStream(el); firstToken = false; }
        appendStream(el, p.token);
      } else if (p.event === 'done') {
        finishStream(el, meta ? `模式：${meta.mode}${meta.auto_generated ? ' · 自动生成' : ''} · 完成` : '完成');
      }
    }
  }
  // 若全程无 token（异常情况），移除指示器
  if (firstToken) {
    el.querySelector('.msg-bubble').innerHTML = '<span class="typing-hint">未收到内容。</span>';
  }
  streamCtrl = null;
}

/* ============================================================
   主流程
   ============================================================ */
async function ask() {
  const q = questionEl.value.trim();
  const endpoint = endpointEl.value;
  const sid = studentIdEl.value.trim() || 'S001';
  if (!q) return questionEl.focus();

  if (streamCtrl) { streamCtrl.abort(); streamCtrl = null; }

  sendBtn.disabled = true; sendBtn.textContent = '…';
  setBusy(true);
  addMsg('user', q, `接口：${endpoint} · ${sid}`);
  msgCount++; memoryCount.textContent = msgCount;

  try {
    if (endpoint === '/ask/stream') {
      const el = showTyping();
      await askStream(q, sid, el);
    } else {
      const el = showTyping();
      try {
        const data = await askNormal(q, endpoint, sid);
        el.remove();
        addMsg('assistant', data.answer, `模式：${data.mode||'-'}${data.auto_generated?' · 自动生成':''}`);
        setStatus(data);
      } catch (e) {
        el.remove();
        throw e;
      }
    }
  } catch (e) {
    if (e.name === 'AbortError') { setBusy(false); return; }
    addMsg('assistant', `请求失败：${e.message}`, '错误', true);
    setStatus({mode:'error',autoGenerated:false,toolsUsed:[],toolResults:{}});
  } finally {
    sendBtn.disabled = false; sendBtn.textContent = '发 送';
    setBusy(false);
    questionEl.focus();
  }
}

async function resetConv() {
  const sid = studentIdEl.value.trim() || 'S001';
  if (streamCtrl) { streamCtrl.abort(); streamCtrl = null; }
  try {
    const res = await fetch('/reset', {method:'POST', headers:headers(), body:JSON.stringify({student_id:sid})});
    const data = await res.json();
    if (data.status === 'ok') {
      msgCount = 0; memoryCount.textContent = '0';
      modeTag.textContent = '已重置'; toolsTag.textContent = '-';
      autoTag.textContent = '-';
      toolResults.textContent = '对话历史已清除。';
      addMsg('assistant', `已清除 ${sid} 的对话历史。`, '系统');
    }
  } catch (e) {
    addMsg('assistant', `重置失败：${e.message}`, '错误', true);
  }
}

/* ============================================================
   事件绑定
   ============================================================ */
$$('[data-preset]').forEach(btn => {
  btn.addEventListener('click', () => {
    questionEl.value = btn.dataset.preset;
    questionEl.focus();
    if (btn.classList.contains('tool-item')) {
      $$('.tool-item').forEach(i => i.classList.remove('active'));
      btn.classList.add('active');
    }
  });
});

// 顶部导航平滑滚动
$$('.top-nav-item').forEach(link => {
  link.addEventListener('click', e => {
    e.preventDefault();
    const t = document.querySelector(link.getAttribute('href'));
    if (t) t.scrollIntoView({behavior:'smooth',block:'start'});
    $$('.top-nav-item').forEach(l => l.classList.remove('active'));
    link.classList.add('active');
  });
});

studentIdEl.addEventListener('input', () => {
  currentSid.textContent = studentIdEl.value.trim() || 'S001';
});

sendBtn.addEventListener('click', ask);
resetBtn.addEventListener('click', resetConv);
themeBtn.addEventListener('click', toggleTheme);
questionEl.addEventListener('keydown', e => {
  if ((e.ctrlKey||e.metaKey) && e.key==='Enter') ask();
});

// 初始化主题
initTheme();
